import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../core/config.dart';
import '../core/pagination.dart';
import '../models/audit_event.dart';
import '../models/subscription.dart';
import '../models/vendor.dart';

class MockAdminFallback {
  const MockAdminFallback();

  Pagination<Vendor> vendors({int page = 1, int pageSize = 20}) {
    final items = List<Vendor>.generate(pageSize, (index) {
      final id = (page - 1) * pageSize + index + 1;
      return Vendor(
        id: id,
        name: 'Mock Vendor $id',
        ownerEmail: 'owner$id@example.com',
        phone: '+910000000$id',
        planCode: index.isEven ? 'pro' : 'starter',
        isActive: index % 3 != 0,
        isVerified: index.isEven,
        onboardingScore: 0.6 + (index % 4) * 0.1,
        createdAt: DateTime.now().subtract(Duration(days: id)),
        notes: 'Generated by mock fallback',
      );
    });

    return Pagination<Vendor>(
      items: items,
      total: 200,
      page: page,
      pageSize: pageSize,
    );
  }

  Pagination<Subscription> subscriptions({int page = 1, int pageSize = 20}) {
    final items = List<Subscription>.generate(pageSize, (index) {
      final id = (page - 1) * pageSize + index + 1;
      return Subscription(
        id: id,
        vendorId: id + 100,
        vendorName: 'Vendor ${id + 100}',
        planId: index.isEven ? 1 : 2,
        planName: index.isEven ? 'Pro Plan' : 'Starter Plan',
        status: index % 3 == 0 ? 'expired' : 'active',
        startsAt: DateTime.now().subtract(Duration(days: id * 2)),
        expiresAt: DateTime.now().add(Duration(days: id * 4)),
        autoRenew: index.isOdd,
        createdAt: DateTime.now().subtract(Duration(days: id * 3)),
      );
    });

    return Pagination<Subscription>(
      items: items,
      total: 120,
      page: page,
      pageSize: pageSize,
    );
  }

  Pagination<AuditEvent> auditLog({int page = 1, int pageSize = 50}) {
    final items = List<AuditEvent>.generate(pageSize, (index) {
      final id = (page - 1) * pageSize + index + 1;
      return AuditEvent(
        id: id,
        adminIdentifier: 'admin@example.com',
        action: index.isEven ? 'vendor.verify' : 'subscription.activate',
        subjectType: index.isEven ? 'vendor' : 'subscription',
        subjectId: '${index + 1}',
        createdAt: DateTime.now().subtract(Duration(minutes: index * 5)),
        payload: {'note': 'Mock audit event $id'},
      );
    });

    return Pagination<AuditEvent>(
      items: items,
      total: 300,
      page: page,
      pageSize: pageSize,
    );
  }
}

final mockAdminFallbackProvider = Provider<MockAdminFallback>((ref) {
  return const MockAdminFallback();
});

final useMockAdminFallbackProvider = StateProvider<bool>((ref) {
  final mockMode = ref.watch(mockModeProvider);
  return mockMode;
});
